status = [
    "static_analysis",
    "build (x86_64-unknown-linux-gnu, ubuntu-latest)",
    "build (armv7-unknown-linux-gnueabihf, ubuntu-latest)",
    "build (x86_64-apple-darwin, macos-latest)",
    "build (x86_64-pc-windows-msvc, windows-latest)",
    "test (ubuntu-latest)",
    "test (macos-latest)",
    "docker_tests (happy_path)",
    "docker_tests (happy_path_restart_bob_after_xmr_locked)",
    "docker_tests (happy_path_restart_alice_after_xmr_locked)",
    "docker_tests (happy_path_restart_bob_before_xmr_locked)",
    "docker_tests (bob_refunds_using_cancel_and_refund_command)",
    "docker_tests (bob_refunds_using_cancel_and_refund_command_timelock_not_expired_force)",
    "docker_tests (bob_refunds_using_cancel_and_refund_command_timelock_not_expired)",
    "docker_tests (punish)",
    "docker_tests (alice_punishes_after_restart_punish_timelock_expired)"
]
